/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "include/google/protobuf/compiler/plugin.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(google_protobuf_compiler_Version, google_protobuf_compiler_Version, AUTO)


PB_BIND(google_protobuf_compiler_CodeGeneratorRequest, google_protobuf_compiler_CodeGeneratorRequest, AUTO)


PB_BIND(google_protobuf_compiler_CodeGeneratorResponse, google_protobuf_compiler_CodeGeneratorResponse, AUTO)


PB_BIND(google_protobuf_compiler_CodeGeneratorResponse_File, google_protobuf_compiler_CodeGeneratorResponse_File, AUTO)





