/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_GOOGLE_PROTOBUF_INCLUDE_GOOGLE_PROTOBUF_API_PB_H_INCLUDED
#define PB_GOOGLE_PROTOBUF_INCLUDE_GOOGLE_PROTOBUF_API_PB_H_INCLUDED
#include <pb.h>
#include "google/protobuf/source_context.pb.h"
#include "google/protobuf/type.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Api is a light-weight descriptor for an API Interface.

 Interfaces are also described as "protocol buffer services" in some contexts,
 such as by the "service" keyword in a .proto file, but they are different
 from API Services, which represent a concrete implementation of an interface
 as opposed to simply a description of methods and bindings. They are also
 sometimes simply referred to as "APIs" in other contexts, such as the name of
 this message itself. See https://cloud.google.com/apis/design/glossary for
 detailed terminology.

 New usages of this message as an alternative to ServiceDescriptorProto are
 strongly discouraged. This message does not reliability preserve all
 information necessary to model the schema and preserve semantics. Instead
 make use of FileDescriptorSet which preserves the necessary information. */
typedef struct _google_protobuf_Api {
    /* The fully qualified name of this interface, including package name
 followed by the interface's simple name. */
    pb_callback_t name;
    /* The methods of this interface, in unspecified order. */
    pb_callback_t methods;
    /* Any metadata attached to the interface. */
    pb_callback_t options;
    /* A version string for this interface. If specified, must have the form
 `major-version.minor-version`, as in `1.10`. If the minor version is
 omitted, it defaults to zero. If the entire version field is empty, the
 major version is derived from the package name, as outlined below. If the
 field is not empty, the version in the package name will be verified to be
 consistent with what is provided here.

 The versioning schema uses [semantic
 versioning](http://semver.org) where the major version number
 indicates a breaking change and the minor version an additive,
 non-breaking change. Both version numbers are signals to users
 what to expect from different versions, and should be carefully
 chosen based on the product plan.

 The major version is also reflected in the package name of the
 interface, which must end in `v<major-version>`, as in
 `google.feature.v1`. For major versions 0 and 1, the suffix can
 be omitted. Zero major versions must only be used for
 experimental, non-GA interfaces. */
    pb_callback_t version;
    /* Source context for the protocol buffer service represented by this
 message. */
    bool has_source_context;
    google_protobuf_SourceContext source_context;
    /* Included interfaces. See [Mixin][]. */
    pb_callback_t mixins;
    /* The source syntax of the service. */
    google_protobuf_Syntax syntax;
    /* The source edition string, only valid when syntax is SYNTAX_EDITIONS. */
    pb_callback_t edition;
} google_protobuf_Api;

/* Method represents a method of an API interface.

 New usages of this message as an alternative to MethodDescriptorProto are
 strongly discouraged. This message does not reliability preserve all
 information necessary to model the schema and preserve semantics. Instead
 make use of FileDescriptorSet which preserves the necessary information. */
typedef struct _google_protobuf_Method {
    /* The simple name of this method. */
    pb_callback_t name;
    /* A URL of the input message type. */
    pb_callback_t request_type_url;
    /* If true, the request is streamed. */
    bool request_streaming;
    /* The URL of the output message type. */
    pb_callback_t response_type_url;
    /* If true, the response is streamed. */
    bool response_streaming;
    /* Any metadata attached to the method. */
    pb_callback_t options;
    /* The source syntax of this method.

 This field should be ignored, instead the syntax should be inherited from
 Api. This is similar to Field and EnumValue. */
    google_protobuf_Syntax syntax;
    /* The source edition string, only valid when syntax is SYNTAX_EDITIONS.

 This field should be ignored, instead the edition should be inherited from
 Api. This is similar to Field and EnumValue. */
    pb_callback_t edition;
} google_protobuf_Method;

/* Declares an API Interface to be included in this interface. The including
 interface must redeclare all the methods from the included interface, but
 documentation and options are inherited as follows:

 - If after comment and whitespace stripping, the documentation
   string of the redeclared method is empty, it will be inherited
   from the original method.

 - Each annotation belonging to the service config (http,
   visibility) which is not set in the redeclared method will be
   inherited.

 - If an http annotation is inherited, the path pattern will be
   modified as follows. Any version prefix will be replaced by the
   version of the including interface plus the [root][] path if
   specified.

 Example of a simple mixin:

     package google.acl.v1;
     service AccessControl {
       // Get the underlying ACL object.
       rpc GetAcl(GetAclRequest) returns (Acl) {
         option (google.api.http).get = "/v1/{resource=**}:getAcl";
       }
     }

     package google.storage.v2;
     service Storage {
       rpc GetAcl(GetAclRequest) returns (Acl);

       // Get a data record.
       rpc GetData(GetDataRequest) returns (Data) {
         option (google.api.http).get = "/v2/{resource=**}";
       }
     }

 Example of a mixin configuration:

     apis:
     - name: google.storage.v2.Storage
       mixins:
       - name: google.acl.v1.AccessControl

 The mixin construct implies that all methods in `AccessControl` are
 also declared with same name and request/response types in
 `Storage`. A documentation generator or annotation processor will
 see the effective `Storage.GetAcl` method after inheriting
 documentation and annotations as follows:

     service Storage {
       // Get the underlying ACL object.
       rpc GetAcl(GetAclRequest) returns (Acl) {
         option (google.api.http).get = "/v2/{resource=**}:getAcl";
       }
       ...
     }

 Note how the version in the path pattern changed from `v1` to `v2`.

 If the `root` field in the mixin is specified, it should be a
 relative path under which inherited HTTP paths are placed. Example:

     apis:
     - name: google.storage.v2.Storage
       mixins:
       - name: google.acl.v1.AccessControl
         root: acls

 This implies the following inherited HTTP annotation:

     service Storage {
       // Get the underlying ACL object.
       rpc GetAcl(GetAclRequest) returns (Acl) {
         option (google.api.http).get = "/v2/acls/{resource=**}:getAcl";
       }
       ...
     } */
typedef struct _google_protobuf_Mixin {
    /* The fully qualified name of the interface which is included. */
    pb_callback_t name;
    /* If non-empty specifies a path under which inherited HTTP paths
 are rooted. */
    pb_callback_t root;
} google_protobuf_Mixin;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define google_protobuf_Api_init_default         {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_SourceContext_init_default, {{NULL}, NULL}, _google_protobuf_Syntax_MIN, {{NULL}, NULL}}
#define google_protobuf_Method_init_default      {{{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, _google_protobuf_Syntax_MIN, {{NULL}, NULL}}
#define google_protobuf_Mixin_init_default       {{{NULL}, NULL}, {{NULL}, NULL}}
#define google_protobuf_Api_init_zero            {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_SourceContext_init_zero, {{NULL}, NULL}, _google_protobuf_Syntax_MIN, {{NULL}, NULL}}
#define google_protobuf_Method_init_zero         {{{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, _google_protobuf_Syntax_MIN, {{NULL}, NULL}}
#define google_protobuf_Mixin_init_zero          {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define google_protobuf_Api_name_tag             1
#define google_protobuf_Api_methods_tag          2
#define google_protobuf_Api_options_tag          3
#define google_protobuf_Api_version_tag          4
#define google_protobuf_Api_source_context_tag   5
#define google_protobuf_Api_mixins_tag           6
#define google_protobuf_Api_syntax_tag           7
#define google_protobuf_Api_edition_tag          8
#define google_protobuf_Method_name_tag          1
#define google_protobuf_Method_request_type_url_tag 2
#define google_protobuf_Method_request_streaming_tag 3
#define google_protobuf_Method_response_type_url_tag 4
#define google_protobuf_Method_response_streaming_tag 5
#define google_protobuf_Method_options_tag       6
#define google_protobuf_Method_syntax_tag        7
#define google_protobuf_Method_edition_tag       8
#define google_protobuf_Mixin_name_tag           1
#define google_protobuf_Mixin_root_tag           2

/* Struct field encoding specification for nanopb */
#define google_protobuf_Api_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  methods,           2) \
X(a, CALLBACK, REPEATED, MESSAGE,  options,           3) \
X(a, CALLBACK, SINGULAR, STRING,   version,           4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  source_context,    5) \
X(a, CALLBACK, REPEATED, MESSAGE,  mixins,            6) \
X(a, STATIC,   SINGULAR, UENUM,    syntax,            7) \
X(a, CALLBACK, SINGULAR, STRING,   edition,           8)
#define google_protobuf_Api_CALLBACK pb_default_field_callback
#define google_protobuf_Api_DEFAULT NULL
#define google_protobuf_Api_methods_MSGTYPE google_protobuf_Method
#define google_protobuf_Api_options_MSGTYPE google_protobuf_Option
#define google_protobuf_Api_source_context_MSGTYPE google_protobuf_SourceContext
#define google_protobuf_Api_mixins_MSGTYPE google_protobuf_Mixin

#define google_protobuf_Method_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, SINGULAR, STRING,   request_type_url,   2) \
X(a, STATIC,   SINGULAR, BOOL,     request_streaming,   3) \
X(a, CALLBACK, SINGULAR, STRING,   response_type_url,   4) \
X(a, STATIC,   SINGULAR, BOOL,     response_streaming,   5) \
X(a, CALLBACK, REPEATED, MESSAGE,  options,           6) \
X(a, STATIC,   SINGULAR, UENUM,    syntax,            7) \
X(a, CALLBACK, SINGULAR, STRING,   edition,           8)
#define google_protobuf_Method_CALLBACK pb_default_field_callback
#define google_protobuf_Method_DEFAULT NULL
#define google_protobuf_Method_options_MSGTYPE google_protobuf_Option

#define google_protobuf_Mixin_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, SINGULAR, STRING,   root,              2)
#define google_protobuf_Mixin_CALLBACK pb_default_field_callback
#define google_protobuf_Mixin_DEFAULT NULL

extern const pb_msgdesc_t google_protobuf_Api_msg;
extern const pb_msgdesc_t google_protobuf_Method_msg;
extern const pb_msgdesc_t google_protobuf_Mixin_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define google_protobuf_Api_fields &google_protobuf_Api_msg
#define google_protobuf_Method_fields &google_protobuf_Method_msg
#define google_protobuf_Mixin_fields &google_protobuf_Mixin_msg

/* Maximum encoded size of messages (where known) */
/* google_protobuf_Api_size depends on runtime parameters */
/* google_protobuf_Method_size depends on runtime parameters */
/* google_protobuf_Mixin_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
