/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "include/google/protobuf/cpp_features.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(pb_CppFeatures, pb_CppFeatures, AUTO)


/* Definition for extension field pb_cpp */
typedef struct _pb_cpp_extmsg {
    pb_CppFeatures cpp;
} pb_cpp_extmsg;
#define pb_cpp_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  cpp,             1000)
#define pb_cpp_extmsg_CALLBACK NULL
#define pb_cpp_extmsg_DEFAULT NULL
#define pb_cpp_extmsg_cpp_MSGTYPE pb_CppFeatures
pb_byte_t pb_cpp_extmsg_default[] = {0x00};
PB_BIND(pb_cpp_extmsg, pb_cpp_extmsg, 2)
const pb_extension_type_t pb_cpp = {
    NULL,
    NULL,
    &pb_cpp_extmsg_msg
};




