/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PB_INCLUDE_GOOGLE_PROTOBUF_GO_FEATURES_PB_H_INCLUDED
#define PB_PB_INCLUDE_GOOGLE_PROTOBUF_GO_FEATURES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _pb_GoFeatures_APILevel {
    /* API_LEVEL_UNSPECIFIED results in selecting the OPEN API,
 but needs to be a separate value to distinguish between
 an explicitly set api level or a missing api level. */
    pb_GoFeatures_APILevel_API_LEVEL_UNSPECIFIED = 0,
    pb_GoFeatures_APILevel_API_OPEN = 1,
    pb_GoFeatures_APILevel_API_HYBRID = 2,
    pb_GoFeatures_APILevel_API_OPAQUE = 3
} pb_GoFeatures_APILevel;

typedef enum _pb_GoFeatures_StripEnumPrefix {
    pb_GoFeatures_StripEnumPrefix_STRIP_ENUM_PREFIX_UNSPECIFIED = 0,
    pb_GoFeatures_StripEnumPrefix_STRIP_ENUM_PREFIX_KEEP = 1,
    pb_GoFeatures_StripEnumPrefix_STRIP_ENUM_PREFIX_GENERATE_BOTH = 2,
    pb_GoFeatures_StripEnumPrefix_STRIP_ENUM_PREFIX_STRIP = 3
} pb_GoFeatures_StripEnumPrefix;

/* Struct definitions */
typedef struct _pb_GoFeatures {
    /* Whether or not to generate the deprecated UnmarshalJSON method for enums.
 Can only be true for proto using the Open Struct api. */
    bool has_legacy_unmarshal_json_enum;
    bool legacy_unmarshal_json_enum;
    /* One of OPEN, HYBRID or OPAQUE. */
    bool has_api_level;
    pb_GoFeatures_APILevel api_level;
    bool has_strip_enum_prefix;
    pb_GoFeatures_StripEnumPrefix strip_enum_prefix;
} pb_GoFeatures;


/* Extensions */
extern const pb_extension_type_t pb_go; /* field type: pb_GoFeatures go; */

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _pb_GoFeatures_APILevel_MIN pb_GoFeatures_APILevel_API_LEVEL_UNSPECIFIED
#define _pb_GoFeatures_APILevel_MAX pb_GoFeatures_APILevel_API_OPAQUE
#define _pb_GoFeatures_APILevel_ARRAYSIZE ((pb_GoFeatures_APILevel)(pb_GoFeatures_APILevel_API_OPAQUE+1))

#define _pb_GoFeatures_StripEnumPrefix_MIN pb_GoFeatures_StripEnumPrefix_STRIP_ENUM_PREFIX_UNSPECIFIED
#define _pb_GoFeatures_StripEnumPrefix_MAX pb_GoFeatures_StripEnumPrefix_STRIP_ENUM_PREFIX_STRIP
#define _pb_GoFeatures_StripEnumPrefix_ARRAYSIZE ((pb_GoFeatures_StripEnumPrefix)(pb_GoFeatures_StripEnumPrefix_STRIP_ENUM_PREFIX_STRIP+1))

#define pb_GoFeatures_api_level_ENUMTYPE pb_GoFeatures_APILevel
#define pb_GoFeatures_strip_enum_prefix_ENUMTYPE pb_GoFeatures_StripEnumPrefix


/* Initializer values for message structs */
#define pb_GoFeatures_init_default               {false, 0, false, _pb_GoFeatures_APILevel_MIN, false, _pb_GoFeatures_StripEnumPrefix_MIN}
#define pb_GoFeatures_init_zero                  {false, 0, false, _pb_GoFeatures_APILevel_MIN, false, _pb_GoFeatures_StripEnumPrefix_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define pb_GoFeatures_legacy_unmarshal_json_enum_tag 1
#define pb_GoFeatures_api_level_tag              2
#define pb_GoFeatures_strip_enum_prefix_tag      3
#define pb_go_tag                                1002

/* Struct field encoding specification for nanopb */
#define pb_GoFeatures_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     legacy_unmarshal_json_enum,   1) \
X(a, STATIC,   OPTIONAL, UENUM,    api_level,         2) \
X(a, STATIC,   OPTIONAL, UENUM,    strip_enum_prefix,   3)
#define pb_GoFeatures_CALLBACK NULL
#define pb_GoFeatures_DEFAULT NULL

extern const pb_msgdesc_t pb_GoFeatures_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define pb_GoFeatures_fields &pb_GoFeatures_msg

/* Maximum encoded size of messages (where known) */
#define PB_INCLUDE_GOOGLE_PROTOBUF_GO_FEATURES_PB_H_MAX_SIZE pb_GoFeatures_size
#define pb_GoFeatures_size                       6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
