/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PB_INCLUDE_GOOGLE_PROTOBUF_JAVA_FEATURES_PB_H_INCLUDED
#define PB_PB_INCLUDE_GOOGLE_PROTOBUF_JAVA_FEATURES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* The UTF8 validation strategy to use. */
typedef enum _pb_JavaFeatures_Utf8Validation {
    /* Invalid default, which should never be used. */
    pb_JavaFeatures_Utf8Validation_UTF8_VALIDATION_UNKNOWN = 0,
    /* Respect the UTF8 validation behavior specified by the global
 utf8_validation feature. */
    pb_JavaFeatures_Utf8Validation_DEFAULT = 1,
    /* Verifies UTF8 validity overriding the global utf8_validation
 feature. This represents the legacy java_string_check_utf8 option. */
    pb_JavaFeatures_Utf8Validation_VERIFY = 2
} pb_JavaFeatures_Utf8Validation;

typedef enum _pb_JavaFeatures_NestInFileClassFeature_NestInFileClass {
    /* Invalid default, which should never be used. */
    pb_JavaFeatures_NestInFileClassFeature_NestInFileClass_NEST_IN_FILE_CLASS_UNKNOWN = 0,
    /* Do not nest the generated class in the file class. */
    pb_JavaFeatures_NestInFileClassFeature_NestInFileClass_NO = 1,
    /* Nest the generated class in the file class. */
    pb_JavaFeatures_NestInFileClassFeature_NestInFileClass_YES = 2,
    /* Fall back to the `java_multiple_files` option. Users won't be able to
 set this option. */
    pb_JavaFeatures_NestInFileClassFeature_NestInFileClass_LEGACY = 3
} pb_JavaFeatures_NestInFileClassFeature_NestInFileClass;

/* Struct definitions */
typedef struct _pb_JavaFeatures {
    /* Whether or not to treat an enum field as closed.  This option is only
 applicable to enum fields, and will be removed in the future.  It is
 consistent with the legacy behavior of using proto3 enum types for proto2
 fields. */
    bool has_legacy_closed_enum;
    bool legacy_closed_enum;
    bool has_utf8_validation;
    pb_JavaFeatures_Utf8Validation utf8_validation;
    /* Allows creation of large Java enums, extending beyond the standard
 constant limits imposed by the Java language. */
    bool has_large_enum;
    bool large_enum;
    /* Whether to use the old default outer class name scheme, or the new feature
 which adds a "Proto" suffix to the outer class name.

 Users will not be able to set this option, because we removed it in the
 same edition that it was introduced. But we use it to determine which
 naming scheme to use for outer class name defaults. */
    bool has_use_old_outer_classname_default;
    bool use_old_outer_classname_default;
    /* Whether to nest the generated class in the generated file class. This is
 only applicable to *top-level* messages, enums, and services. */
    bool has_nest_in_file_class;
    pb_JavaFeatures_NestInFileClassFeature_NestInFileClass nest_in_file_class;
} pb_JavaFeatures;

typedef struct _pb_JavaFeatures_NestInFileClassFeature {
    char dummy_field;
} pb_JavaFeatures_NestInFileClassFeature;


/* Extensions */
extern const pb_extension_type_t pb_java; /* field type: pb_JavaFeatures java; */

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _pb_JavaFeatures_Utf8Validation_MIN pb_JavaFeatures_Utf8Validation_UTF8_VALIDATION_UNKNOWN
#define _pb_JavaFeatures_Utf8Validation_MAX pb_JavaFeatures_Utf8Validation_VERIFY
#define _pb_JavaFeatures_Utf8Validation_ARRAYSIZE ((pb_JavaFeatures_Utf8Validation)(pb_JavaFeatures_Utf8Validation_VERIFY+1))

#define _pb_JavaFeatures_NestInFileClassFeature_NestInFileClass_MIN pb_JavaFeatures_NestInFileClassFeature_NestInFileClass_NEST_IN_FILE_CLASS_UNKNOWN
#define _pb_JavaFeatures_NestInFileClassFeature_NestInFileClass_MAX pb_JavaFeatures_NestInFileClassFeature_NestInFileClass_LEGACY
#define _pb_JavaFeatures_NestInFileClassFeature_NestInFileClass_ARRAYSIZE ((pb_JavaFeatures_NestInFileClassFeature_NestInFileClass)(pb_JavaFeatures_NestInFileClassFeature_NestInFileClass_LEGACY+1))

#define pb_JavaFeatures_utf8_validation_ENUMTYPE pb_JavaFeatures_Utf8Validation
#define pb_JavaFeatures_nest_in_file_class_ENUMTYPE pb_JavaFeatures_NestInFileClassFeature_NestInFileClass



/* Initializer values for message structs */
#define pb_JavaFeatures_init_default             {false, 0, false, _pb_JavaFeatures_Utf8Validation_MIN, false, 0, false, 0, false, _pb_JavaFeatures_NestInFileClassFeature_NestInFileClass_MIN}
#define pb_JavaFeatures_NestInFileClassFeature_init_default {0}
#define pb_JavaFeatures_init_zero                {false, 0, false, _pb_JavaFeatures_Utf8Validation_MIN, false, 0, false, 0, false, _pb_JavaFeatures_NestInFileClassFeature_NestInFileClass_MIN}
#define pb_JavaFeatures_NestInFileClassFeature_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define pb_JavaFeatures_legacy_closed_enum_tag   1
#define pb_JavaFeatures_utf8_validation_tag      2
#define pb_JavaFeatures_large_enum_tag           3
#define pb_JavaFeatures_use_old_outer_classname_default_tag 4
#define pb_JavaFeatures_nest_in_file_class_tag   5
#define pb_java_tag                              1001

/* Struct field encoding specification for nanopb */
#define pb_JavaFeatures_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     legacy_closed_enum,   1) \
X(a, STATIC,   OPTIONAL, UENUM,    utf8_validation,   2) \
X(a, STATIC,   OPTIONAL, BOOL,     large_enum,        3) \
X(a, STATIC,   OPTIONAL, BOOL,     use_old_outer_classname_default,   4) \
X(a, STATIC,   OPTIONAL, UENUM,    nest_in_file_class,   5)
#define pb_JavaFeatures_CALLBACK NULL
#define pb_JavaFeatures_DEFAULT NULL

#define pb_JavaFeatures_NestInFileClassFeature_FIELDLIST(X, a) \

#define pb_JavaFeatures_NestInFileClassFeature_CALLBACK NULL
#define pb_JavaFeatures_NestInFileClassFeature_DEFAULT NULL

extern const pb_msgdesc_t pb_JavaFeatures_msg;
extern const pb_msgdesc_t pb_JavaFeatures_NestInFileClassFeature_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define pb_JavaFeatures_fields &pb_JavaFeatures_msg
#define pb_JavaFeatures_NestInFileClassFeature_fields &pb_JavaFeatures_NestInFileClassFeature_msg

/* Maximum encoded size of messages (where known) */
#define PB_INCLUDE_GOOGLE_PROTOBUF_JAVA_FEATURES_PB_H_MAX_SIZE pb_JavaFeatures_size
#define pb_JavaFeatures_NestInFileClassFeature_size 0
#define pb_JavaFeatures_size                     10

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
