/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_GOOGLE_PROTOBUF_INCLUDE_GOOGLE_PROTOBUF_TYPE_PB_H_INCLUDED
#define PB_GOOGLE_PROTOBUF_INCLUDE_GOOGLE_PROTOBUF_TYPE_PB_H_INCLUDED
#include <pb.h>
#include "google/protobuf/any.pb.h"
#include "google/protobuf/source_context.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* The syntax in which a protocol buffer element is defined. */
typedef enum _google_protobuf_Syntax {
    /* Syntax `proto2`. */
    google_protobuf_Syntax_SYNTAX_PROTO2 = 0,
    /* Syntax `proto3`. */
    google_protobuf_Syntax_SYNTAX_PROTO3 = 1,
    /* Syntax `editions`. */
    google_protobuf_Syntax_SYNTAX_EDITIONS = 2
} google_protobuf_Syntax;

/* Basic field types. */
typedef enum _google_protobuf_Field_Kind {
    /* Field type unknown. */
    google_protobuf_Field_Kind_TYPE_UNKNOWN = 0,
    /* Field type double. */
    google_protobuf_Field_Kind_TYPE_DOUBLE = 1,
    /* Field type float. */
    google_protobuf_Field_Kind_TYPE_FLOAT = 2,
    /* Field type int64. */
    google_protobuf_Field_Kind_TYPE_INT64 = 3,
    /* Field type uint64. */
    google_protobuf_Field_Kind_TYPE_UINT64 = 4,
    /* Field type int32. */
    google_protobuf_Field_Kind_TYPE_INT32 = 5,
    /* Field type fixed64. */
    google_protobuf_Field_Kind_TYPE_FIXED64 = 6,
    /* Field type fixed32. */
    google_protobuf_Field_Kind_TYPE_FIXED32 = 7,
    /* Field type bool. */
    google_protobuf_Field_Kind_TYPE_BOOL = 8,
    /* Field type string. */
    google_protobuf_Field_Kind_TYPE_STRING = 9,
    /* Field type group. Proto2 syntax only, and deprecated. */
    google_protobuf_Field_Kind_TYPE_GROUP = 10,
    /* Field type message. */
    google_protobuf_Field_Kind_TYPE_MESSAGE = 11,
    /* Field type bytes. */
    google_protobuf_Field_Kind_TYPE_BYTES = 12,
    /* Field type uint32. */
    google_protobuf_Field_Kind_TYPE_UINT32 = 13,
    /* Field type enum. */
    google_protobuf_Field_Kind_TYPE_ENUM = 14,
    /* Field type sfixed32. */
    google_protobuf_Field_Kind_TYPE_SFIXED32 = 15,
    /* Field type sfixed64. */
    google_protobuf_Field_Kind_TYPE_SFIXED64 = 16,
    /* Field type sint32. */
    google_protobuf_Field_Kind_TYPE_SINT32 = 17,
    /* Field type sint64. */
    google_protobuf_Field_Kind_TYPE_SINT64 = 18
} google_protobuf_Field_Kind;

/* Whether a field is optional, required, or repeated. */
typedef enum _google_protobuf_Field_Cardinality {
    /* For fields with unknown cardinality. */
    google_protobuf_Field_Cardinality_CARDINALITY_UNKNOWN = 0,
    /* For optional fields. */
    google_protobuf_Field_Cardinality_CARDINALITY_OPTIONAL = 1,
    /* For required fields. Proto2 syntax only. */
    google_protobuf_Field_Cardinality_CARDINALITY_REQUIRED = 2,
    /* For repeated fields. */
    google_protobuf_Field_Cardinality_CARDINALITY_REPEATED = 3
} google_protobuf_Field_Cardinality;

/* Struct definitions */
/* A protocol buffer message type.

 New usages of this message as an alternative to DescriptorProto are strongly
 discouraged. This message does not reliability preserve all information
 necessary to model the schema and preserve semantics. Instead make use of
 FileDescriptorSet which preserves the necessary information. */
typedef struct _google_protobuf_Type {
    /* The fully qualified message name. */
    pb_callback_t name;
    /* The list of fields. */
    pb_callback_t fields;
    /* The list of types appearing in `oneof` definitions in this type. */
    pb_callback_t oneofs;
    /* The protocol buffer options. */
    pb_callback_t options;
    /* The source context. */
    bool has_source_context;
    google_protobuf_SourceContext source_context;
    /* The source syntax. */
    google_protobuf_Syntax syntax;
    /* The source edition string, only valid when syntax is SYNTAX_EDITIONS. */
    pb_callback_t edition;
} google_protobuf_Type;

/* A single field of a message type.

 New usages of this message as an alternative to FieldDescriptorProto are
 strongly discouraged. This message does not reliability preserve all
 information necessary to model the schema and preserve semantics. Instead
 make use of FileDescriptorSet which preserves the necessary information. */
typedef struct _google_protobuf_Field {
    /* The field type. */
    google_protobuf_Field_Kind kind;
    /* The field cardinality. */
    google_protobuf_Field_Cardinality cardinality;
    /* The field number. */
    int32_t number;
    /* The field name. */
    pb_callback_t name;
    /* The field type URL, without the scheme, for message or enumeration
 types. Example: `"type.googleapis.com/google.protobuf.Timestamp"`. */
    pb_callback_t type_url;
    /* The index of the field type in `Type.oneofs`, for message or enumeration
 types. The first type has index 1; zero means the type is not in the list. */
    int32_t oneof_index;
    /* Whether to use alternative packed wire representation. */
    bool packed;
    /* The protocol buffer options. */
    pb_callback_t options;
    /* The field JSON name. */
    pb_callback_t json_name;
    /* The string value of the default value of this field. Proto2 syntax only. */
    pb_callback_t default_value;
} google_protobuf_Field;

/* Enum type definition.

 New usages of this message as an alternative to EnumDescriptorProto are
 strongly discouraged. This message does not reliability preserve all
 information necessary to model the schema and preserve semantics. Instead
 make use of FileDescriptorSet which preserves the necessary information. */
typedef struct _google_protobuf_Enum {
    /* Enum type name. */
    pb_callback_t name;
    /* Enum value definitions. */
    pb_callback_t enumvalue;
    /* Protocol buffer options. */
    pb_callback_t options;
    /* The source context. */
    bool has_source_context;
    google_protobuf_SourceContext source_context;
    /* The source syntax. */
    google_protobuf_Syntax syntax;
    /* The source edition string, only valid when syntax is SYNTAX_EDITIONS. */
    pb_callback_t edition;
} google_protobuf_Enum;

/* Enum value definition.

 New usages of this message as an alternative to EnumValueDescriptorProto are
 strongly discouraged. This message does not reliability preserve all
 information necessary to model the schema and preserve semantics. Instead
 make use of FileDescriptorSet which preserves the necessary information. */
typedef struct _google_protobuf_EnumValue {
    /* Enum value name. */
    pb_callback_t name;
    /* Enum value number. */
    int32_t number;
    /* Protocol buffer options. */
    pb_callback_t options;
} google_protobuf_EnumValue;

/* A protocol buffer option, which can be attached to a message, field,
 enumeration, etc.

 New usages of this message as an alternative to FileOptions, MessageOptions,
 FieldOptions, EnumOptions, EnumValueOptions, ServiceOptions, or MethodOptions
 are strongly discouraged. */
typedef struct _google_protobuf_Option {
    /* The option's name. For protobuf built-in options (options defined in
 descriptor.proto), this is the short name. For example, `"map_entry"`.
 For custom options, it should be the fully-qualified name. For example,
 `"google.api.http"`. */
    pb_callback_t name;
    /* The option's value packed in an Any message. If the value is a primitive,
 the corresponding wrapper type defined in google/protobuf/wrappers.proto
 should be used. If the value is an enum, it should be stored as an int32
 value using the google.protobuf.Int32Value type. */
    bool has_value;
    google_protobuf_Any value;
} google_protobuf_Option;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _google_protobuf_Syntax_MIN google_protobuf_Syntax_SYNTAX_PROTO2
#define _google_protobuf_Syntax_MAX google_protobuf_Syntax_SYNTAX_EDITIONS
#define _google_protobuf_Syntax_ARRAYSIZE ((google_protobuf_Syntax)(google_protobuf_Syntax_SYNTAX_EDITIONS+1))

#define _google_protobuf_Field_Kind_MIN google_protobuf_Field_Kind_TYPE_UNKNOWN
#define _google_protobuf_Field_Kind_MAX google_protobuf_Field_Kind_TYPE_SINT64
#define _google_protobuf_Field_Kind_ARRAYSIZE ((google_protobuf_Field_Kind)(google_protobuf_Field_Kind_TYPE_SINT64+1))

#define _google_protobuf_Field_Cardinality_MIN google_protobuf_Field_Cardinality_CARDINALITY_UNKNOWN
#define _google_protobuf_Field_Cardinality_MAX google_protobuf_Field_Cardinality_CARDINALITY_REPEATED
#define _google_protobuf_Field_Cardinality_ARRAYSIZE ((google_protobuf_Field_Cardinality)(google_protobuf_Field_Cardinality_CARDINALITY_REPEATED+1))

#define google_protobuf_Type_syntax_ENUMTYPE google_protobuf_Syntax

#define google_protobuf_Field_kind_ENUMTYPE google_protobuf_Field_Kind
#define google_protobuf_Field_cardinality_ENUMTYPE google_protobuf_Field_Cardinality

#define google_protobuf_Enum_syntax_ENUMTYPE google_protobuf_Syntax




/* Initializer values for message structs */
#define google_protobuf_Type_init_default        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_SourceContext_init_default, _google_protobuf_Syntax_MIN, {{NULL}, NULL}}
#define google_protobuf_Field_init_default       {_google_protobuf_Field_Kind_MIN, _google_protobuf_Field_Cardinality_MIN, 0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define google_protobuf_Enum_init_default        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_SourceContext_init_default, _google_protobuf_Syntax_MIN, {{NULL}, NULL}}
#define google_protobuf_EnumValue_init_default   {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define google_protobuf_Option_init_default      {{{NULL}, NULL}, false, google_protobuf_Any_init_default}
#define google_protobuf_Type_init_zero           {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_SourceContext_init_zero, _google_protobuf_Syntax_MIN, {{NULL}, NULL}}
#define google_protobuf_Field_init_zero          {_google_protobuf_Field_Kind_MIN, _google_protobuf_Field_Cardinality_MIN, 0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define google_protobuf_Enum_init_zero           {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_SourceContext_init_zero, _google_protobuf_Syntax_MIN, {{NULL}, NULL}}
#define google_protobuf_EnumValue_init_zero      {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define google_protobuf_Option_init_zero         {{{NULL}, NULL}, false, google_protobuf_Any_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define google_protobuf_Type_name_tag            1
#define google_protobuf_Type_fields_tag          2
#define google_protobuf_Type_oneofs_tag          3
#define google_protobuf_Type_options_tag         4
#define google_protobuf_Type_source_context_tag  5
#define google_protobuf_Type_syntax_tag          6
#define google_protobuf_Type_edition_tag         7
#define google_protobuf_Field_kind_tag           1
#define google_protobuf_Field_cardinality_tag    2
#define google_protobuf_Field_number_tag         3
#define google_protobuf_Field_name_tag           4
#define google_protobuf_Field_type_url_tag       6
#define google_protobuf_Field_oneof_index_tag    7
#define google_protobuf_Field_packed_tag         8
#define google_protobuf_Field_options_tag        9
#define google_protobuf_Field_json_name_tag      10
#define google_protobuf_Field_default_value_tag  11
#define google_protobuf_Enum_name_tag            1
#define google_protobuf_Enum_enumvalue_tag       2
#define google_protobuf_Enum_options_tag         3
#define google_protobuf_Enum_source_context_tag  4
#define google_protobuf_Enum_syntax_tag          5
#define google_protobuf_Enum_edition_tag         6
#define google_protobuf_EnumValue_name_tag       1
#define google_protobuf_EnumValue_number_tag     2
#define google_protobuf_EnumValue_options_tag    3
#define google_protobuf_Option_name_tag          1
#define google_protobuf_Option_value_tag         2

/* Struct field encoding specification for nanopb */
#define google_protobuf_Type_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  fields,            2) \
X(a, CALLBACK, REPEATED, STRING,   oneofs,            3) \
X(a, CALLBACK, REPEATED, MESSAGE,  options,           4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  source_context,    5) \
X(a, STATIC,   SINGULAR, UENUM,    syntax,            6) \
X(a, CALLBACK, SINGULAR, STRING,   edition,           7)
#define google_protobuf_Type_CALLBACK pb_default_field_callback
#define google_protobuf_Type_DEFAULT NULL
#define google_protobuf_Type_fields_MSGTYPE google_protobuf_Field
#define google_protobuf_Type_options_MSGTYPE google_protobuf_Option
#define google_protobuf_Type_source_context_MSGTYPE google_protobuf_SourceContext

#define google_protobuf_Field_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    kind,              1) \
X(a, STATIC,   SINGULAR, UENUM,    cardinality,       2) \
X(a, STATIC,   SINGULAR, INT32,    number,            3) \
X(a, CALLBACK, SINGULAR, STRING,   name,              4) \
X(a, CALLBACK, SINGULAR, STRING,   type_url,          6) \
X(a, STATIC,   SINGULAR, INT32,    oneof_index,       7) \
X(a, STATIC,   SINGULAR, BOOL,     packed,            8) \
X(a, CALLBACK, REPEATED, MESSAGE,  options,           9) \
X(a, CALLBACK, SINGULAR, STRING,   json_name,        10) \
X(a, CALLBACK, SINGULAR, STRING,   default_value,    11)
#define google_protobuf_Field_CALLBACK pb_default_field_callback
#define google_protobuf_Field_DEFAULT NULL
#define google_protobuf_Field_options_MSGTYPE google_protobuf_Option

#define google_protobuf_Enum_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  enumvalue,         2) \
X(a, CALLBACK, REPEATED, MESSAGE,  options,           3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  source_context,    4) \
X(a, STATIC,   SINGULAR, UENUM,    syntax,            5) \
X(a, CALLBACK, SINGULAR, STRING,   edition,           6)
#define google_protobuf_Enum_CALLBACK pb_default_field_callback
#define google_protobuf_Enum_DEFAULT NULL
#define google_protobuf_Enum_enumvalue_MSGTYPE google_protobuf_EnumValue
#define google_protobuf_Enum_options_MSGTYPE google_protobuf_Option
#define google_protobuf_Enum_source_context_MSGTYPE google_protobuf_SourceContext

#define google_protobuf_EnumValue_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, INT32,    number,            2) \
X(a, CALLBACK, REPEATED, MESSAGE,  options,           3)
#define google_protobuf_EnumValue_CALLBACK pb_default_field_callback
#define google_protobuf_EnumValue_DEFAULT NULL
#define google_protobuf_EnumValue_options_MSGTYPE google_protobuf_Option

#define google_protobuf_Option_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define google_protobuf_Option_CALLBACK pb_default_field_callback
#define google_protobuf_Option_DEFAULT NULL
#define google_protobuf_Option_value_MSGTYPE google_protobuf_Any

extern const pb_msgdesc_t google_protobuf_Type_msg;
extern const pb_msgdesc_t google_protobuf_Field_msg;
extern const pb_msgdesc_t google_protobuf_Enum_msg;
extern const pb_msgdesc_t google_protobuf_EnumValue_msg;
extern const pb_msgdesc_t google_protobuf_Option_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define google_protobuf_Type_fields &google_protobuf_Type_msg
#define google_protobuf_Field_fields &google_protobuf_Field_msg
#define google_protobuf_Enum_fields &google_protobuf_Enum_msg
#define google_protobuf_EnumValue_fields &google_protobuf_EnumValue_msg
#define google_protobuf_Option_fields &google_protobuf_Option_msg

/* Maximum encoded size of messages (where known) */
/* google_protobuf_Type_size depends on runtime parameters */
/* google_protobuf_Field_size depends on runtime parameters */
/* google_protobuf_Enum_size depends on runtime parameters */
/* google_protobuf_EnumValue_size depends on runtime parameters */
/* google_protobuf_Option_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
