// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: proto/service.proto

package serviceManagerProject

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CurrentState int32

const (
	CurrentState_ALIVE         CurrentState = 0
	CurrentState_DEAD          CurrentState = 1
	CurrentState_CONNECTING    CurrentState = 2
	CurrentState_DISCONNECTING CurrentState = 3
	CurrentState_RECONNECTING  CurrentState = 4
	CurrentState_ERROR         CurrentState = 5
)

// Enum value maps for CurrentState.
var (
	CurrentState_name = map[int32]string{
		0: "ALIVE",
		1: "DEAD",
		2: "CONNECTING",
		3: "DISCONNECTING",
		4: "RECONNECTING",
		5: "ERROR",
	}
	CurrentState_value = map[string]int32{
		"ALIVE":         0,
		"DEAD":          1,
		"CONNECTING":    2,
		"DISCONNECTING": 3,
		"RECONNECTING":  4,
		"ERROR":         5,
	}
)

func (x CurrentState) Enum() *CurrentState {
	p := new(CurrentState)
	*p = x
	return p
}

func (x CurrentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CurrentState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_service_proto_enumTypes[0].Descriptor()
}

func (CurrentState) Type() protoreflect.EnumType {
	return &file_proto_service_proto_enumTypes[0]
}

func (x CurrentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CurrentState.Descriptor instead.
func (CurrentState) EnumDescriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Descriptor_   *BaseReply             `protobuf:"bytes,1,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	State         CurrentState           `protobuf:"varint,2,opt,name=state,proto3,enum=ServicePackage.CurrentState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *State) GetDescriptor_() *BaseReply {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *State) GetState() CurrentState {
	if x != nil {
		return x.State
	}
	return CurrentState_ALIVE
}

type BaseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=lastUpdated,proto3" json:"lastUpdated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseReply) Reset() {
	*x = BaseReply{}
	mi := &file_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseReply) ProtoMessage() {}

func (x *BaseReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseReply.ProtoReflect.Descriptor instead.
func (*BaseReply) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *BaseReply) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BaseReply) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

var File_proto_service_proto protoreflect.FileDescriptor

const file_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x13proto/service.proto\x12\x0eServicePackage\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"v\n" +
	"\x05State\x129\n" +
	"\n" +
	"descriptor\x18\x01 \x01(\v2\x19.ServicePackage.BaseReplyR\n" +
	"descriptor\x122\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1c.ServicePackage.CurrentStateR\x05state\"Y\n" +
	"\tBaseReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12<\n" +
	"\vlastUpdated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated*c\n" +
	"\fCurrentState\x12\t\n" +
	"\x05ALIVE\x10\x00\x12\b\n" +
	"\x04DEAD\x10\x01\x12\x0e\n" +
	"\n" +
	"CONNECTING\x10\x02\x12\x11\n" +
	"\rDISCONNECTING\x10\x03\x12\x10\n" +
	"\fRECONNECTING\x10\x04\x12\t\n" +
	"\x05ERROR\x10\x052\x8c\x03\n" +
	"\aService\x125\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x15.ServicePackage.State\x12;\n" +
	"\aConnect\x12\x19.ServicePackage.BaseReply\x1a\x15.ServicePackage.State\x12>\n" +
	"\n" +
	"Disconnect\x12\x19.ServicePackage.BaseReply\x1a\x15.ServicePackage.State\x12H\n" +
	"\x13PropagateCachedLogs\x12\x19.ServicePackage.BaseReply\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\x10GetCurrentStatus\x12\x19.ServicePackage.BaseReply\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\bGetState\x12\x19.ServicePackage.BaseReply\x1a\x15.ServicePackage.StateBRZPgithub.com/ghosthookcc/HomeAutomatonKit/app/ServiceManager/serviceManagerProjectb\x06proto3"

var (
	file_proto_service_proto_rawDescOnce sync.Once
	file_proto_service_proto_rawDescData []byte
)

func file_proto_service_proto_rawDescGZIP() []byte {
	file_proto_service_proto_rawDescOnce.Do(func() {
		file_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)))
	})
	return file_proto_service_proto_rawDescData
}

var file_proto_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_service_proto_goTypes = []any{
	(CurrentState)(0),             // 0: ServicePackage.CurrentState
	(*State)(nil),                 // 1: ServicePackage.State
	(*BaseReply)(nil),             // 2: ServicePackage.BaseReply
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 4: google.protobuf.Empty
}
var file_proto_service_proto_depIdxs = []int32{
	2, // 0: ServicePackage.State.descriptor:type_name -> ServicePackage.BaseReply
	0, // 1: ServicePackage.State.state:type_name -> ServicePackage.CurrentState
	3, // 2: ServicePackage.BaseReply.lastUpdated:type_name -> google.protobuf.Timestamp
	4, // 3: ServicePackage.Service.Ping:input_type -> google.protobuf.Empty
	2, // 4: ServicePackage.Service.Connect:input_type -> ServicePackage.BaseReply
	2, // 5: ServicePackage.Service.Disconnect:input_type -> ServicePackage.BaseReply
	2, // 6: ServicePackage.Service.PropagateCachedLogs:input_type -> ServicePackage.BaseReply
	2, // 7: ServicePackage.Service.GetCurrentStatus:input_type -> ServicePackage.BaseReply
	2, // 8: ServicePackage.Service.GetState:input_type -> ServicePackage.BaseReply
	1, // 9: ServicePackage.Service.Ping:output_type -> ServicePackage.State
	1, // 10: ServicePackage.Service.Connect:output_type -> ServicePackage.State
	1, // 11: ServicePackage.Service.Disconnect:output_type -> ServicePackage.State
	4, // 12: ServicePackage.Service.PropagateCachedLogs:output_type -> google.protobuf.Empty
	4, // 13: ServicePackage.Service.GetCurrentStatus:output_type -> google.protobuf.Empty
	1, // 14: ServicePackage.Service.GetState:output_type -> ServicePackage.State
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_service_proto_init() }
func file_proto_service_proto_init() {
	if File_proto_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_proto_goTypes,
		DependencyIndexes: file_proto_service_proto_depIdxs,
		EnumInfos:         file_proto_service_proto_enumTypes,
		MessageInfos:      file_proto_service_proto_msgTypes,
	}.Build()
	File_proto_service_proto = out.File
	file_proto_service_proto_goTypes = nil
	file_proto_service_proto_depIdxs = nil
}
