/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SENSOR_DATA_COLLECTION_IMPL_SENSOR_DATA_COLLECTION_SERVICE_SENSOR_DATA_COLLECTION_SERVICE_PB_H_INCLUDED
#define PB_SENSOR_DATA_COLLECTION_IMPL_SENSOR_DATA_COLLECTION_SERVICE_SENSOR_DATA_COLLECTION_SERVICE_PB_H_INCLUDED
#include <pb.h>
#include "../../include/google/protobuf/timestamp.pb.h"
#include "../../common/service.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _sensor_data_collection_SensorData {
    int32_t humidityPercent;
    bool has_sendAt;
    google_protobuf_Timestamp sendAt;
} sensor_data_collection_SensorData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define sensor_data_collection_SensorData_init_default {0, false, google_protobuf_Timestamp_init_default}
#define sensor_data_collection_SensorData_init_zero {0, false, google_protobuf_Timestamp_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define sensor_data_collection_SensorData_humidityPercent_tag 1
#define sensor_data_collection_SensorData_sendAt_tag 2

/* Struct field encoding specification for nanopb */
#define sensor_data_collection_SensorData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    humidityPercent,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sendAt,            2)
#define sensor_data_collection_SensorData_CALLBACK NULL
#define sensor_data_collection_SensorData_DEFAULT NULL
#define sensor_data_collection_SensorData_sendAt_MSGTYPE google_protobuf_Timestamp

extern const pb_msgdesc_t sensor_data_collection_SensorData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define sensor_data_collection_SensorData_fields &sensor_data_collection_SensorData_msg

/* Maximum encoded size of messages (where known) */
#define SENSOR_DATA_COLLECTION_IMPL_SENSOR_DATA_COLLECTION_SERVICE_SENSOR_DATA_COLLECTION_SERVICE_PB_H_MAX_SIZE sensor_data_collection_SensorData_size
#define sensor_data_collection_SensorData_size   35

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
