/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "sensor-data-collection-service.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(sensor_data_collection_SensorData, sensor_data_collection_SensorData, AUTO)



