// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: impl/echo-service/echo-service.proto

package echo_service

import (
	_ "github.com/ghosthookcc/HomeAutomatonKit/app/ServiceManager/proto-stubs/impl/go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_impl_echo_service_echo_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_impl_echo_service_echo_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_impl_echo_service_echo_service_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_impl_echo_service_echo_service_proto protoreflect.FileDescriptor

const file_impl_echo_service_echo_service_proto_rawDesc = "" +
	"\n" +
	"$impl/echo-service/echo-service.proto\x12\x04echo\x1a\x14common/service.proto\"\x1d\n" +
	"\aMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data23\n" +
	"\vEchoService\x12$\n" +
	"\x04Echo\x12\r.echo.Message\x1a\r.echo.MessageBZZXgithub.com/ghosthookcc/HomeAutomatonKit/app/ServiceManager/proto-stubs/impl/echo-serviceb\x06proto3"

var (
	file_impl_echo_service_echo_service_proto_rawDescOnce sync.Once
	file_impl_echo_service_echo_service_proto_rawDescData []byte
)

func file_impl_echo_service_echo_service_proto_rawDescGZIP() []byte {
	file_impl_echo_service_echo_service_proto_rawDescOnce.Do(func() {
		file_impl_echo_service_echo_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_impl_echo_service_echo_service_proto_rawDesc), len(file_impl_echo_service_echo_service_proto_rawDesc)))
	})
	return file_impl_echo_service_echo_service_proto_rawDescData
}

var file_impl_echo_service_echo_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_impl_echo_service_echo_service_proto_goTypes = []any{
	(*Message)(nil), // 0: echo.Message
}
var file_impl_echo_service_echo_service_proto_depIdxs = []int32{
	0, // 0: echo.EchoService.Echo:input_type -> echo.Message
	0, // 1: echo.EchoService.Echo:output_type -> echo.Message
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_impl_echo_service_echo_service_proto_init() }
func file_impl_echo_service_echo_service_proto_init() {
	if File_impl_echo_service_echo_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_impl_echo_service_echo_service_proto_rawDesc), len(file_impl_echo_service_echo_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_impl_echo_service_echo_service_proto_goTypes,
		DependencyIndexes: file_impl_echo_service_echo_service_proto_depIdxs,
		MessageInfos:      file_impl_echo_service_echo_service_proto_msgTypes,
	}.Build()
	File_impl_echo_service_echo_service_proto = out.File
	file_impl_echo_service_echo_service_proto_goTypes = nil
	file_impl_echo_service_echo_service_proto_depIdxs = nil
}
