/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "common/service.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ServicePackage_BaseState, ServicePackage_BaseState, AUTO)


PB_BIND(ServicePackage_BaseHeartbeat, ServicePackage_BaseHeartbeat, AUTO)





