/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SERVICEPACKAGE_COMMON_SERVICE_PB_H_INCLUDED
#define PB_SERVICEPACKAGE_COMMON_SERVICE_PB_H_INCLUDED
#include <pb.h>
#include "../include/google/protobuf/empty.pb.h"
#include "../include/google/protobuf/timestamp.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _ServicePackage_ConnectionState {
    ServicePackage_ConnectionState_ALIVE = 0,
    ServicePackage_ConnectionState_DEAD = 1,
    ServicePackage_ConnectionState_CONNECTING = 2,
    ServicePackage_ConnectionState_DISCONNECTING = 3,
    ServicePackage_ConnectionState_RECONNECTING = 4,
    ServicePackage_ConnectionState_ERROR = 5
} ServicePackage_ConnectionState;

/* Struct definitions */
typedef struct _ServicePackage_BaseHeartbeat {
    int32_t id;
    bool has_lastUpdated;
    google_protobuf_Timestamp lastUpdated;
} ServicePackage_BaseHeartbeat;

typedef struct _ServicePackage_BaseState {
    bool has_heartbeat;
    ServicePackage_BaseHeartbeat heartbeat;
    ServicePackage_ConnectionState state;
} ServicePackage_BaseState;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ServicePackage_ConnectionState_MIN ServicePackage_ConnectionState_ALIVE
#define _ServicePackage_ConnectionState_MAX ServicePackage_ConnectionState_ERROR
#define _ServicePackage_ConnectionState_ARRAYSIZE ((ServicePackage_ConnectionState)(ServicePackage_ConnectionState_ERROR+1))

#define ServicePackage_BaseState_state_ENUMTYPE ServicePackage_ConnectionState



/* Initializer values for message structs */
#define ServicePackage_BaseState_init_default    {false, ServicePackage_BaseHeartbeat_init_default, _ServicePackage_ConnectionState_MIN}
#define ServicePackage_BaseHeartbeat_init_default {0, false, google_protobuf_Timestamp_init_default}
#define ServicePackage_BaseState_init_zero       {false, ServicePackage_BaseHeartbeat_init_zero, _ServicePackage_ConnectionState_MIN}
#define ServicePackage_BaseHeartbeat_init_zero   {0, false, google_protobuf_Timestamp_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define ServicePackage_BaseHeartbeat_id_tag      1
#define ServicePackage_BaseHeartbeat_lastUpdated_tag 2
#define ServicePackage_BaseState_heartbeat_tag   1
#define ServicePackage_BaseState_state_tag       2

/* Struct field encoding specification for nanopb */
#define ServicePackage_BaseState_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  heartbeat,         1) \
X(a, STATIC,   SINGULAR, UENUM,    state,             2)
#define ServicePackage_BaseState_CALLBACK NULL
#define ServicePackage_BaseState_DEFAULT NULL
#define ServicePackage_BaseState_heartbeat_MSGTYPE ServicePackage_BaseHeartbeat

#define ServicePackage_BaseHeartbeat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  lastUpdated,       2)
#define ServicePackage_BaseHeartbeat_CALLBACK NULL
#define ServicePackage_BaseHeartbeat_DEFAULT NULL
#define ServicePackage_BaseHeartbeat_lastUpdated_MSGTYPE google_protobuf_Timestamp

extern const pb_msgdesc_t ServicePackage_BaseState_msg;
extern const pb_msgdesc_t ServicePackage_BaseHeartbeat_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ServicePackage_BaseState_fields &ServicePackage_BaseState_msg
#define ServicePackage_BaseHeartbeat_fields &ServicePackage_BaseHeartbeat_msg

/* Maximum encoded size of messages (where known) */
#define SERVICEPACKAGE_COMMON_SERVICE_PB_H_MAX_SIZE ServicePackage_BaseState_size
#define ServicePackage_BaseHeartbeat_size        35
#define ServicePackage_BaseState_size            39

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
