/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ECHO_IMPL_ECHO_SERVICE_ECHO_SERVICE_PB_H_INCLUDED
#define PB_ECHO_IMPL_ECHO_SERVICE_ECHO_SERVICE_PB_H_INCLUDED
#include <pb.h>
#include "../../common/service.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _echo_Message {
    pb_callback_t data;
} echo_Message;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define echo_Message_init_default                {{{NULL}, NULL}}
#define echo_Message_init_zero                   {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define echo_Message_data_tag                    1

/* Struct field encoding specification for nanopb */
#define echo_Message_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   data,              1)
#define echo_Message_CALLBACK pb_default_field_callback
#define echo_Message_DEFAULT NULL

extern const pb_msgdesc_t echo_Message_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define echo_Message_fields &echo_Message_msg

/* Maximum encoded size of messages (where known) */
/* echo_Message_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
