/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_GOOGLE_PROTOBUF_COMPILER_INCLUDE_GOOGLE_PROTOBUF_COMPILER_PLUGIN_PB_H_INCLUDED
#define PB_GOOGLE_PROTOBUF_COMPILER_INCLUDE_GOOGLE_PROTOBUF_COMPILER_PLUGIN_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Sync with code_generator.h. */
typedef enum _google_protobuf_compiler_CodeGeneratorResponse_Feature {
    google_protobuf_compiler_CodeGeneratorResponse_Feature_FEATURE_NONE = 0,
    google_protobuf_compiler_CodeGeneratorResponse_Feature_FEATURE_PROTO3_OPTIONAL = 1,
    google_protobuf_compiler_CodeGeneratorResponse_Feature_FEATURE_SUPPORTS_EDITIONS = 2
} google_protobuf_compiler_CodeGeneratorResponse_Feature;

/* Struct definitions */
/* The version number of protocol compiler. */
typedef struct _google_protobuf_compiler_Version {
    bool has_major;
    int32_t major;
    bool has_minor;
    int32_t minor;
    bool has_patch;
    int32_t patch;
    /* A suffix for alpha, beta or rc release, e.g., "alpha-1", "rc2". It should
 be empty for mainline stable releases. */
    pb_callback_t suffix;
} google_protobuf_compiler_Version;

/* An encoded CodeGeneratorRequest is written to the plugin's stdin. */
typedef struct _google_protobuf_compiler_CodeGeneratorRequest {
    /* The .proto files that were explicitly listed on the command-line.  The
 code generator should generate code only for these files.  Each file's
 descriptor will be included in proto_file, below. */
    pb_callback_t file_to_generate;
    /* The generator parameter passed on the command-line. */
    pb_callback_t parameter;
    /* The version number of protocol compiler. */
    bool has_compiler_version;
    google_protobuf_compiler_Version compiler_version;
    /* FileDescriptorProtos for all files in files_to_generate and everything
 they import.  The files will appear in topological order, so each file
 appears before any file that imports it.

 Note: the files listed in files_to_generate will include runtime-retention
 options only, but all other files will include source-retention options.
 The source_file_descriptors field below is available in case you need
 source-retention options for files_to_generate.

 protoc guarantees that all proto_files will be written after
 the fields above, even though this is not technically guaranteed by the
 protobuf wire format.  This theoretically could allow a plugin to stream
 in the FileDescriptorProtos and handle them one by one rather than read
 the entire set into memory at once.  However, as of this writing, this
 is not similarly optimized on protoc's end -- it will store all fields in
 memory at once before sending them to the plugin.

 Type names of fields and extensions in the FileDescriptorProto are always
 fully qualified. */
    pb_callback_t proto_file;
    /* File descriptors with all options, including source-retention options.
 These descriptors are only provided for the files listed in
 files_to_generate. */
    pb_callback_t source_file_descriptors;
} google_protobuf_compiler_CodeGeneratorRequest;

/* The plugin writes an encoded CodeGeneratorResponse to stdout. */
typedef struct _google_protobuf_compiler_CodeGeneratorResponse {
    /* Error message.  If non-empty, code generation failed.  The plugin process
 should exit with status code zero even if it reports an error in this way.

 This should be used to indicate errors in .proto files which prevent the
 code generator from generating correct code.  Errors which indicate a
 problem in protoc itself -- such as the input CodeGeneratorRequest being
 unparseable -- should be reported by writing a message to stderr and
 exiting with a non-zero status code. */
    pb_callback_t error;
    /* A bitmask of supported features that the code generator supports.
 This is a bitwise "or" of values from the Feature enum. */
    bool has_supported_features;
    uint64_t supported_features;
    /* The minimum edition this plugin supports.  This will be treated as an
 Edition enum, but we want to allow unknown values.  It should be specified
 according the edition enum value, *not* the edition number.  Only takes
 effect for plugins that have FEATURE_SUPPORTS_EDITIONS set. */
    bool has_minimum_edition;
    int32_t minimum_edition;
    /* The maximum edition this plugin supports.  This will be treated as an
 Edition enum, but we want to allow unknown values.  It should be specified
 according the edition enum value, *not* the edition number.  Only takes
 effect for plugins that have FEATURE_SUPPORTS_EDITIONS set. */
    bool has_maximum_edition;
    int32_t maximum_edition;
    pb_callback_t file;
} google_protobuf_compiler_CodeGeneratorResponse;

/* Represents a single generated file. */
typedef struct _google_protobuf_compiler_CodeGeneratorResponse_File {
    /* The file name, relative to the output directory.  The name must not
 contain "." or ".." components and must be relative, not be absolute (so,
 the file cannot lie outside the output directory).  "/" must be used as
 the path separator, not "\".

 If the name is omitted, the content will be appended to the previous
 file.  This allows the generator to break large files into small chunks,
 and allows the generated text to be streamed back to protoc so that large
 files need not reside completely in memory at one time.  Note that as of
 this writing protoc does not optimize for this -- it will read the entire
 CodeGeneratorResponse before writing files to disk. */
    pb_callback_t name;
    /* If non-empty, indicates that the named file should already exist, and the
 content here is to be inserted into that file at a defined insertion
 point.  This feature allows a code generator to extend the output
 produced by another code generator.  The original generator may provide
 insertion points by placing special annotations in the file that look
 like:
   @@protoc_insertion_point(NAME)
 The annotation can have arbitrary text before and after it on the line,
 which allows it to be placed in a comment.  NAME should be replaced with
 an identifier naming the point -- this is what other generators will use
 as the insertion_point.  Code inserted at this point will be placed
 immediately above the line containing the insertion point (thus multiple
 insertions to the same point will come out in the order they were added).
 The double-@ is intended to make it unlikely that the generated code
 could contain things that look like insertion points by accident.

 For example, the C++ code generator places the following line in the
 .pb.h files that it generates:
   // @@protoc_insertion_point(namespace_scope)
 This line appears within the scope of the file's package namespace, but
 outside of any particular class.  Another plugin can then specify the
 insertion_point "namespace_scope" to generate additional classes or
 other declarations that should be placed in this scope.

 Note that if the line containing the insertion point begins with
 whitespace, the same whitespace will be added to every line of the
 inserted text.  This is useful for languages like Python, where
 indentation matters.  In these languages, the insertion point comment
 should be indented the same amount as any inserted code will need to be
 in order to work correctly in that context.

 The code generator that generates the initial file and the one which
 inserts into it must both run as part of a single invocation of protoc.
 Code generators are executed in the order in which they appear on the
 command line.

 If |insertion_point| is present, |name| must also be present. */
    pb_callback_t insertion_point;
    /* The file contents. */
    pb_callback_t content;
    /* Information describing the file content being inserted. If an insertion
 point is used, this information will be appropriately offset and inserted
 into the code generation metadata for the generated files. */
    bool has_generated_code_info;
    google_protobuf_GeneratedCodeInfo generated_code_info;
} google_protobuf_compiler_CodeGeneratorResponse_File;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _google_protobuf_compiler_CodeGeneratorResponse_Feature_MIN google_protobuf_compiler_CodeGeneratorResponse_Feature_FEATURE_NONE
#define _google_protobuf_compiler_CodeGeneratorResponse_Feature_MAX google_protobuf_compiler_CodeGeneratorResponse_Feature_FEATURE_SUPPORTS_EDITIONS
#define _google_protobuf_compiler_CodeGeneratorResponse_Feature_ARRAYSIZE ((google_protobuf_compiler_CodeGeneratorResponse_Feature)(google_protobuf_compiler_CodeGeneratorResponse_Feature_FEATURE_SUPPORTS_EDITIONS+1))






/* Initializer values for message structs */
#define google_protobuf_compiler_Version_init_default {false, 0, false, 0, false, 0, {{NULL}, NULL}}
#define google_protobuf_compiler_CodeGeneratorRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_compiler_Version_init_default, {{NULL}, NULL}, {{NULL}, NULL}}
#define google_protobuf_compiler_CodeGeneratorResponse_init_default {{{NULL}, NULL}, false, 0, false, 0, false, 0, {{NULL}, NULL}}
#define google_protobuf_compiler_CodeGeneratorResponse_File_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_GeneratedCodeInfo_init_default}
#define google_protobuf_compiler_Version_init_zero {false, 0, false, 0, false, 0, {{NULL}, NULL}}
#define google_protobuf_compiler_CodeGeneratorRequest_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_compiler_Version_init_zero, {{NULL}, NULL}, {{NULL}, NULL}}
#define google_protobuf_compiler_CodeGeneratorResponse_init_zero {{{NULL}, NULL}, false, 0, false, 0, false, 0, {{NULL}, NULL}}
#define google_protobuf_compiler_CodeGeneratorResponse_File_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_GeneratedCodeInfo_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define google_protobuf_compiler_Version_major_tag 1
#define google_protobuf_compiler_Version_minor_tag 2
#define google_protobuf_compiler_Version_patch_tag 3
#define google_protobuf_compiler_Version_suffix_tag 4
#define google_protobuf_compiler_CodeGeneratorRequest_file_to_generate_tag 1
#define google_protobuf_compiler_CodeGeneratorRequest_parameter_tag 2
#define google_protobuf_compiler_CodeGeneratorRequest_compiler_version_tag 3
#define google_protobuf_compiler_CodeGeneratorRequest_proto_file_tag 15
#define google_protobuf_compiler_CodeGeneratorRequest_source_file_descriptors_tag 17
#define google_protobuf_compiler_CodeGeneratorResponse_error_tag 1
#define google_protobuf_compiler_CodeGeneratorResponse_supported_features_tag 2
#define google_protobuf_compiler_CodeGeneratorResponse_minimum_edition_tag 3
#define google_protobuf_compiler_CodeGeneratorResponse_maximum_edition_tag 4
#define google_protobuf_compiler_CodeGeneratorResponse_file_tag 15
#define google_protobuf_compiler_CodeGeneratorResponse_File_name_tag 1
#define google_protobuf_compiler_CodeGeneratorResponse_File_insertion_point_tag 2
#define google_protobuf_compiler_CodeGeneratorResponse_File_content_tag 15
#define google_protobuf_compiler_CodeGeneratorResponse_File_generated_code_info_tag 16

/* Struct field encoding specification for nanopb */
#define google_protobuf_compiler_Version_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    major,             1) \
X(a, STATIC,   OPTIONAL, INT32,    minor,             2) \
X(a, STATIC,   OPTIONAL, INT32,    patch,             3) \
X(a, CALLBACK, OPTIONAL, STRING,   suffix,            4)
#define google_protobuf_compiler_Version_CALLBACK pb_default_field_callback
#define google_protobuf_compiler_Version_DEFAULT NULL

#define google_protobuf_compiler_CodeGeneratorRequest_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   file_to_generate,   1) \
X(a, CALLBACK, OPTIONAL, STRING,   parameter,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  compiler_version,   3) \
X(a, CALLBACK, REPEATED, MESSAGE,  proto_file,       15) \
X(a, CALLBACK, REPEATED, MESSAGE,  source_file_descriptors,  17)
#define google_protobuf_compiler_CodeGeneratorRequest_CALLBACK pb_default_field_callback
#define google_protobuf_compiler_CodeGeneratorRequest_DEFAULT NULL
#define google_protobuf_compiler_CodeGeneratorRequest_compiler_version_MSGTYPE google_protobuf_compiler_Version
#define google_protobuf_compiler_CodeGeneratorRequest_proto_file_MSGTYPE google_protobuf_FileDescriptorProto
#define google_protobuf_compiler_CodeGeneratorRequest_source_file_descriptors_MSGTYPE google_protobuf_FileDescriptorProto

#define google_protobuf_compiler_CodeGeneratorResponse_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   error,             1) \
X(a, STATIC,   OPTIONAL, UINT64,   supported_features,   2) \
X(a, STATIC,   OPTIONAL, INT32,    minimum_edition,   3) \
X(a, STATIC,   OPTIONAL, INT32,    maximum_edition,   4) \
X(a, CALLBACK, REPEATED, MESSAGE,  file,             15)
#define google_protobuf_compiler_CodeGeneratorResponse_CALLBACK pb_default_field_callback
#define google_protobuf_compiler_CodeGeneratorResponse_DEFAULT NULL
#define google_protobuf_compiler_CodeGeneratorResponse_file_MSGTYPE google_protobuf_compiler_CodeGeneratorResponse_File

#define google_protobuf_compiler_CodeGeneratorResponse_File_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   name,              1) \
X(a, CALLBACK, OPTIONAL, STRING,   insertion_point,   2) \
X(a, CALLBACK, OPTIONAL, STRING,   content,          15) \
X(a, STATIC,   OPTIONAL, MESSAGE,  generated_code_info,  16)
#define google_protobuf_compiler_CodeGeneratorResponse_File_CALLBACK pb_default_field_callback
#define google_protobuf_compiler_CodeGeneratorResponse_File_DEFAULT NULL
#define google_protobuf_compiler_CodeGeneratorResponse_File_generated_code_info_MSGTYPE google_protobuf_GeneratedCodeInfo

extern const pb_msgdesc_t google_protobuf_compiler_Version_msg;
extern const pb_msgdesc_t google_protobuf_compiler_CodeGeneratorRequest_msg;
extern const pb_msgdesc_t google_protobuf_compiler_CodeGeneratorResponse_msg;
extern const pb_msgdesc_t google_protobuf_compiler_CodeGeneratorResponse_File_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define google_protobuf_compiler_Version_fields &google_protobuf_compiler_Version_msg
#define google_protobuf_compiler_CodeGeneratorRequest_fields &google_protobuf_compiler_CodeGeneratorRequest_msg
#define google_protobuf_compiler_CodeGeneratorResponse_fields &google_protobuf_compiler_CodeGeneratorResponse_msg
#define google_protobuf_compiler_CodeGeneratorResponse_File_fields &google_protobuf_compiler_CodeGeneratorResponse_File_msg

/* Maximum encoded size of messages (where known) */
/* google_protobuf_compiler_Version_size depends on runtime parameters */
/* google_protobuf_compiler_CodeGeneratorRequest_size depends on runtime parameters */
/* google_protobuf_compiler_CodeGeneratorResponse_size depends on runtime parameters */
/* google_protobuf_compiler_CodeGeneratorResponse_File_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
