/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PB_INCLUDE_GOOGLE_PROTOBUF_CPP_FEATURES_PB_H_INCLUDED
#define PB_PB_INCLUDE_GOOGLE_PROTOBUF_CPP_FEATURES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _pb_CppFeatures_StringType {
    pb_CppFeatures_StringType_STRING_TYPE_UNKNOWN = 0,
    pb_CppFeatures_StringType_VIEW = 1,
    pb_CppFeatures_StringType_CORD = 2,
    pb_CppFeatures_StringType_STRING = 3
} pb_CppFeatures_StringType;

/* Struct definitions */
typedef struct _pb_CppFeatures {
    /* Whether or not to treat an enum field as closed.  This option is only
 applicable to enum fields, and will be removed in the future.  It is
 consistent with the legacy behavior of using proto3 enum types for proto2
 fields. */
    bool has_legacy_closed_enum;
    bool legacy_closed_enum;
    bool has_string_type;
    pb_CppFeatures_StringType string_type;
    bool has_enum_name_uses_string_view;
    bool enum_name_uses_string_view;
} pb_CppFeatures;


/* Extensions */
extern const pb_extension_type_t pb_cpp; /* field type: pb_CppFeatures cpp; */

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _pb_CppFeatures_StringType_MIN pb_CppFeatures_StringType_STRING_TYPE_UNKNOWN
#define _pb_CppFeatures_StringType_MAX pb_CppFeatures_StringType_STRING
#define _pb_CppFeatures_StringType_ARRAYSIZE ((pb_CppFeatures_StringType)(pb_CppFeatures_StringType_STRING+1))

#define pb_CppFeatures_string_type_ENUMTYPE pb_CppFeatures_StringType


/* Initializer values for message structs */
#define pb_CppFeatures_init_default              {false, 0, false, _pb_CppFeatures_StringType_MIN, false, 0}
#define pb_CppFeatures_init_zero                 {false, 0, false, _pb_CppFeatures_StringType_MIN, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define pb_CppFeatures_legacy_closed_enum_tag    1
#define pb_CppFeatures_string_type_tag           2
#define pb_CppFeatures_enum_name_uses_string_view_tag 3
#define pb_cpp_tag                               1000

/* Struct field encoding specification for nanopb */
#define pb_CppFeatures_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     legacy_closed_enum,   1) \
X(a, STATIC,   OPTIONAL, UENUM,    string_type,       2) \
X(a, STATIC,   OPTIONAL, BOOL,     enum_name_uses_string_view,   3)
#define pb_CppFeatures_CALLBACK NULL
#define pb_CppFeatures_DEFAULT NULL

extern const pb_msgdesc_t pb_CppFeatures_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define pb_CppFeatures_fields &pb_CppFeatures_msg

/* Maximum encoded size of messages (where known) */
#define PB_INCLUDE_GOOGLE_PROTOBUF_CPP_FEATURES_PB_H_MAX_SIZE pb_CppFeatures_size
#define pb_CppFeatures_size                      6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
