/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "include/google/protobuf/go_features.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(pb_GoFeatures, pb_GoFeatures, AUTO)


/* Definition for extension field pb_go */
typedef struct _pb_go_extmsg {
    pb_GoFeatures go;
} pb_go_extmsg;
#define pb_go_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  go,              1002)
#define pb_go_extmsg_CALLBACK NULL
#define pb_go_extmsg_DEFAULT NULL
#define pb_go_extmsg_go_MSGTYPE pb_GoFeatures
pb_byte_t pb_go_extmsg_default[] = {0x00};
PB_BIND(pb_go_extmsg, pb_go_extmsg, 2)
const pb_extension_type_t pb_go = {
    NULL,
    NULL,
    &pb_go_extmsg_msg
};






