/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "include/google/protobuf/java_features.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(pb_JavaFeatures, pb_JavaFeatures, AUTO)


PB_BIND(pb_JavaFeatures_NestInFileClassFeature, pb_JavaFeatures_NestInFileClassFeature, AUTO)


/* Definition for extension field pb_java */
typedef struct _pb_java_extmsg {
    pb_JavaFeatures java;
} pb_java_extmsg;
#define pb_java_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  java,            1001)
#define pb_java_extmsg_CALLBACK NULL
#define pb_java_extmsg_DEFAULT NULL
#define pb_java_extmsg_java_MSGTYPE pb_JavaFeatures
pb_byte_t pb_java_extmsg_default[] = {0x00};
PB_BIND(pb_java_extmsg, pb_java_extmsg, 2)
const pb_extension_type_t pb_java = {
    NULL,
    NULL,
    &pb_java_extmsg_msg
};






